# データベース接続情報
spring.datasource.url=jdbc:mysql://localhost:3306/onlinestore?serverTimezone=Asia/Tokyo&useSSL=false
spring.datasource.username=mik
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA設定
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
